[config]
schemaVersion = "0.0.1"

[package]
namespace = "hermesdj"
name = "VRising Server Events Plugin"
versionNumber = "1.0.0"
description = "Server Events plugin used unify events management"
websiteUrl = "https://github.com/hermesdj/VRisingServerEvents"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.668.5"
gg.deca.Bloodstone = "0.8.0"

[build]
icon = "./images/logo_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://v-rising.thunderstore.io"
communities = ["v-rising"]
categories = ["gloomrot-update", "mods", "server"]